version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: ror_elasticsearch
    hostname: ror_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    networks:
      - elk_Network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    container_name: ror_logstash
    hostname: ror_logstash
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk_Network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: ror_kibana
    hostname: ror_kibana
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    environment:
      - xpack.security.enabled=true
    networks:
      - elk_Network

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml

networks:
  elk_Network:
    driver: bridge
